// Path: /Users/rakeshkainthla/development/programming-language/cpplox//Stmt.h
// This file was automatically generated by generateAST.cpp
#pragma once
#include "./Expr.h"
#include "./token.h"
#include <any>
#include <iostream>
#include <memory>
#include <optional>
class If;
class Block;
class Expression;
class Print;
class Var;
using Stmt = std::variant<std::shared_ptr<If>, std::shared_ptr<Block>,
                          std::shared_ptr<Expression>, std::shared_ptr<Print>,
                          std::shared_ptr<Var>>;
class If {
public:
  If(Expr condition, Stmt thenBranch, std::optional<Stmt> elseBranch)
      : condition(condition), thenBranch(thenBranch), elseBranch(elseBranch) {}
  const Expr condition;
  const Stmt thenBranch;
  const std::optional<Stmt> elseBranch;
};
class Block {
public:
  Block(std::vector<Stmt> statements) : statements(statements) {}
  const std::vector<Stmt> statements;
};
class Expression {
public:
  Expression(Expr expression) : expression(expression) {}
  const Expr expression;
};
class Print {
public:
  Print(Expr expression) : expression(expression) {}
  const Expr expression;
};
class Var {
public:
  Var(Token name, std::optional<Expr> initializer)
      : name(name), initializer(initializer) {}
  const Token name;
  const std::optional<Expr> initializer;
};
